# Generated by Django 5.1.2 on 2025-08-29 05:07

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def add_sample_data(apps, schema_editor):
    TravelOption = apps.get_model('booking', 'TravelOption')
    
    # Add sample travel options
    sample_travels = [
        {
            'type': 'Flight',
            'source': 'Mumbai',
            'destination': 'Delhi',
            'date_time': timezone.now() + timedelta(days=1, hours=10),
            'price': 8500.00,
            'available_seats': 45
        },
        {
            'type': 'Flight',
            'source': 'Delhi',
            'destination': 'Bangalore',
            'date_time': timezone.now() + timedelta(days=2, hours=14),
            'price': 9200.00,
            'available_seats': 32
        },
        {
            'type': 'Train',
            'source': 'Mumbai',
            'destination': 'Pune',
            'date_time': timezone.now() + timedelta(days=1, hours=8),
            'price': 450.00,
            'available_seats': 120
        },
        {
            'type': 'Train',
            'source': 'Delhi',
            'destination': 'Agra',
            'date_time': timezone.now() + timedelta(days=3, hours=6),
            'price': 280.00,
            'available_seats': 85
        },
        {
            'type': 'Bus',
            'source': 'Mumbai',
            'destination': 'Nashik',
            'date_time': timezone.now() + timedelta(days=1, hours=7),
            'price': 350.00,
            'available_seats': 25
        },
        {
            'type': 'Bus',
            'source': 'Pune',
            'destination': 'Mumbai',
            'date_time': timezone.now() + timedelta(days=2, hours=9),
            'price': 400.00,
            'available_seats': 30
        }
    ]
    
    for travel_data in sample_travels:
        TravelOption.objects.create(**travel_data)

def remove_sample_data(apps, schema_editor):
    TravelOption = apps.get_model('booking', 'TravelOption')
    TravelOption.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data, remove_sample_data),
    ]
